name: Build and deploy Node.js app to Git Pages

on:
  push:
    branches:
      - new_deploy

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # POSTBUILD SCRIPT
      - name: Create build for client
        run: NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client
